### ISSUE TITLE
15.3 の softmax_cross_entorpy の数式誤り?

### ISSUE THREAD

**Issue by fumuumuf** [chainer/tutorials#13]
とてもわかり易いチュートリアルありがとうございます.

タイトルの件について 
15.3. Step 3 : 目的関数を決める（応用編）   
の 2 式目の y_k とt_k は逆ではないかと思われます.

**Comment by mitmul** [comment]
@fumuumuf フィードバックありがとうございます． #16 にて修正させていただきます．

**Comment by fumuumuf** [comment]
ご対応ありがとうございました.
