### ISSUE TITLE
Typo in a figure in 13.3.2. 

### ISSUE THREAD

**Issue by akinomaeni** [chainer/tutorials#14]
I found a typo in [a figure](https://github.com/chainer/tutorials/blob/6b5e1aee7e/ja/images/11/11_03.png) in [13.3.2. 線形変換](https://tutorials.chainer.org/ja/src/13_Basics_of_Neural_Networks_ja.html#%E7%B7%9A%E5%BD%A2%E5%A4%89%E6%8F%9B).
"w31" is supposed to be "w23".

**Comment by mitmul** [comment]
#35 にて修正させていただきました。ご報告ありがとうございました。
