### ISSUE TITLE
5.1 の行列について

### ISSUE THREAD

**Issue by yasuhiro1988** [chainer/tutorials#17]
5.1 の行列の説明についてです。

・ベクトルの要素を縦方向に並べたものは列ベクトルと呼ぶ
・ベクトルの要素を横方向に並べたものは行ベクトルと呼ぶ
このような定義の後に行列(matrix)の説明がありますが、

・行列の形（サイズ）は行数と列数で表現する
例えば、 X は3行2列なので…

行列の一例として表示されている図(Xの表記)を見ますと、
縦方向の要素が3、横方向の要素が2ありますので
先述の前提から解釈を試みますと、正しくは3列2行ではないか。
このような混乱が生じる可能性がありますので、
何かもう一言補足があるとよいのではないかと感じました。

あまり良い表現は思いつきませんでしたが、
横一行を行、縦一列を列と呼ぶが、行数は縦方向に数え、列数は横方向に数えるといったくだりがあってもよいかもしれませんが、少しくどい感じもしますので

行列の形（サイズ）は行数（縦方向の要素数）と列数（横方向の要素数）で表現します。

くらいの表記でも腑に落ちるきっかけに繋がるのではと思い、提案とさせていただきます。
説明が過ぎるということでしたら、却下していただいて構いません。

**Comment by delta2323** [comment]
ありがとうございます．「列ベクトル」「行ベクトル」「3行2列」の言葉の使い方はこれが一般的だと思うのですが，指摘された混乱は起こりうると思うので，補足説明が会ったほうがいいかなと思います

**Comment by delta2323** [comment]
例えば，こんな感じではどうでしょう：

例えば上に挙げたXは行ベクトルが3つ並んだものと思えます．そのためXの行数は3です．一方，見方を変えるとXは列ベクトルが2つ並んだものとも思えるのでXの列数は2です．そこで，Xは「3行2列の行列」と呼びます，「サイズが(3, 2)の行列」「サイズ3x2の行列」と呼んでも構いません．

**Comment by yasuhiro1988** [comment]
delta2323様

コメント頂き、ありがとうございます。

とても分かりやすい説明ですので、
すんなりと読み進められるかと思います。

是非是非、反映していただけたら幸いです。

どのチュートリアルも大変読みやすく
うろ覚えだったり昔に放り投げてしまった分野でも読むと不思議と染み込んでくる感じがいたします。

ありがとうございました。

**Comment by delta2323** [comment]
ありがとうございます．こちら修正のPull Requestを作成しました（https://github.com/chainer/tutorials/pull/20）．
また，チュートリアルに関してもお褒めのご感想いただきありがとうございます．読み進めていって気になる点がありましたらぜひフィードバックをいただけると大変助かります
