### ISSUE TITLE
5.5.2. 計算例 のヤコビ行列の向きについて

### ISSUE THREAD

**Issue by Masa-Shin** [chainer/tutorials#18]
下記画像ですが、fの偏微分、gの偏微分ともに転置してしまっていないでしょうか。

![無題](https://user-images.githubusercontent.com/34234442/57161979-e36f1a80-6e27-11e9-94e0-b1545eadb950.png)

実際この向きだと積が定義できないと思われます。また、5.5.1のヤコビ行列とも向きが異なっています。

**Comment by delta2323** [comment]
ありがとうございます．ご指摘の通り，f, gのヤコビ行列が両方とも転置したものになっており正しくありません．修正する必要があります
