### ISSUE TITLE
How about adding the link to description of this repo?

### ISSUE THREAD

**Issue by crcrpar** [chainer/tutorials#2]
Kudos to this great work 🎉 

But how about adding the link (https://tutorials.chainer.org/) to the description of this repository?
![image](https://user-images.githubusercontent.com/16191443/55886034-f9513d00-5be5-11e9-8b9c-9ce8e289258b.png)

**Comment by mitmul** [comment]
Thanks! Added descriptions to the top of this repo. 👍
