### ISSUE TITLE
Step1の演習問題:問2.1(組み込み関数)の公式ドキュメントのURL

### ISSUE THREAD

**Issue by pay2940** [chainer/tutorials#24]
tutorials/ja/Exercise_Step_01_ja.ipynb 24行目
問2.1(組み込み関数)の公式ドキュメントのURLを「https://tutorials.chainer.org/ja/<https://docs.python.org/ja/3/library/functions.html>」と設定しておりアクセス不可のため，URL先を確認ください．

**Comment by mitmul** [comment]
ご指摘ありがとうございます。修正いたしました。ご確認ください。
https://tutorials.chainer.org/ja/src/Exercise_Step_01_ja.html
