### ISSUE TITLE
Step1の演習問題:問5.1.5の関数

### ISSUE THREAD

**Issue by pay2940** [chainer/tutorials#25]
tutorials/ja/Exercise_Step_01_ja.ipynb 493行目

> def matrix_transpose(X):
>     \# ...
> X = [[1, 2, 3],
>         [4, 5, 6]]
> answer = matrix_transpose(X, y)
> print(answer)  # => [[1, 4], [2, 5], [3, 6]]

matrix_transposeの定義とanswerを算出するときの引数が一致していないので確認ください．

**Comment by mitmul** [comment]
ご指摘ありがとうございます。修正いたしました。ご確認ください。
https://tutorials.chainer.org/ja/src/Exercise_Step_01_ja.html#%E5%95%8F5.1-(%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0%E3%81%AB%E3%81%8A%E3%81%91%E3%82%8B%E3%83%99%E3%82%AF%E3%83%88%E3%83%AB%E3%83%BB%E8%A1%8C%E5%88%97%E3%81%AE%E8%A8%88%E7%AE%97)
