### ISSUE TITLE
Step1の演習問題:問5.2 (3)の二次形式の微分

### ISSUE THREAD

**Issue by pay2940** [chainer/tutorials#26]
tutorials/ja/Exercise_Step_01_ja.ipynb 537行目

> これによって <img src="https://latex.codecogs.com/gif.latex?\frac{\partial}{\partial&space;\boldsymbol{x}}\left(&space;\boldsymbol{x^T&space;\boldsymbol{A}&space;x}&space;\right)&space;=&space;\left(\boldsymbol{A}&space;&plus;&space;\boldsymbol{A}^T&space;\right)&space;\boldsymbol{x}"> が成り立つことを確かめて下さい。

とありますが，5.1.10 (3)にもある通り以下が成り立つと思うのですが確認ください．
<img src="https://latex.codecogs.com/gif.latex?\frac{\partial}{\partial&space;\boldsymbol{x}}\left(&space;\boldsymbol{x^T&space;\boldsymbol{A}&space;x}&space;\right)&space;=&space;\boldsymbol{x}^T&space;\left(\boldsymbol{A}&space;&plus;&space;\boldsymbol{A}^T&space;\right)">

**Comment by ir5** [comment]
ありがとうございます。ご指摘の通り 5.1.10 (3) にある式が正しいです。修正します。

**Comment by mitmul** [comment]
Fixed.
