### ISSUE TITLE
15. Chainerの応用:15.4 Step4:最適化手法を選択する（応用編）

### ISSUE THREAD

**Issue by pay2940** [chainer/tutorials#27]
tutorials/ja/15_Advanced_Usage_of_Chainer_ja.ipynb 553行目

> <img src ="https://latex.codecogs.com/gif.latex?\Delta&space;w_t&space;=&space;\frac{\partial&space;L(\boldsymbol\Theta)}{\partial&space;w^{(t)}}&space;\\&space;w&space;\leftarrow&space;w&space;-&space;\eta&space;\Delta&space;x_{t}&space;&plus;&space;\mu&space;\Delta&space;x_{t&space;-&space;1}">.
> ここで、t 回目の更新量を<img src="https://latex.codecogs.com/gif.latex?\Delta&space;x_t$">とおいています。 また、μ は前回更新量に掛ける係数で、多くの場合 0.9 程度が用いられます。 これを前節で解説した重み減衰と合わせて用いると、更新式は以下のようになります。
> <img src="https://latex.codecogs.com/gif.latex?w&space;\leftarrow&space;w&space;-&space;\eta&space;\Delta&space;x_{t}&space;&plus;&space;\mu&space;\Delta&space;x_{t&space;-&space;1}-\eta&\lambda&w">

１つ目の式には更新量<img src="https://latex.codecogs.com/gif.latex?\Delta&space;w_t$">，2つ目/3つ目の式と本文中には更新量<img src="https://latex.codecogs.com/gif.latex?\Delta&space;x_t$">と，更新量の変数が混在していると思うので確認ください．

（16章までのチュートリアルを終えて気になった箇所をあげさせてもらっています．わかりやすいチュートリアルで良かったです．）

**Comment by mitmul** [comment]
フィードバックありがとうございます。確認いたします。

> わかりやすいチュートリアルで良かったです．

そう言っていただけて大変幸いです。お読みくださいましてありがとうございます。

**Comment by mitmul** [comment]
こちらのコミットでfixされましたので、closeいたします。https://github.com/chainer/tutorials/commit/62a8052527644037ca3a26e0e09ebac52cd9512e
