### ISSUE TITLE
2.8.1. 関数を定義する: 図のヘッダ部分の最後の：（コロン）が抜けています

### ISSUE THREAD

**Issue by satoshi8732** [chainer/tutorials#29]

**Comment by mitmul** [comment]
@satoshi8732 ご報告ありがとうございます。修正いたします。

**Comment by mitmul** [comment]
修正いたしました。ご確認ください。
https://tutorials.chainer.org/ja/src/02_Basics_of_Python_ja.html#関数を定義する
