### ISSUE TITLE
2.6.1のリストのスライスの説明について

### ISSUE THREAD

**Issue by shioshiota** [chainer/tutorials#31]
2.6.1のリストのスライスの説明の

https://github.com/chainer/tutorials/blob/master/ja/02_Basics_of_Python.ipynb?short_path=6c74742#L2844

上記部分、

> ここで、2 個目の要素自体は**後半部に含まれる**ということに注意してください。

について

> ここで、インデックス番号が 2 の要素自体は後半部に含まれるということに注意してください。

としたほうが正確なのかと思いました。
(n個目という表現は、1オリジンで他は記載されており、伝えたいことはこうなのかな、と)

よろしくお願いします。

**Comment by mitmul** [comment]
ご報告ありがとうございます。こちらの commit で修正いたしましたのでクローズさせていただきます。https://github.com/chainer/tutorials/commit/d4c6b952eb53b1e1a867332ea08d8310b65c14bc
