### ISSUE TITLE
tutorial 5.5.1項　計算において不要行あり？

### ISSUE THREAD

**Issue by nagayamashota** [chainer/tutorials#6]
スクリーンショット最下部、
∂f/du(u) の途中計算において行列が4*4とになっていますが、3*4ではないでしょうか？

<img width="839" alt="スクリーンショット 2019-04-12 18 45 38" src="https://user-images.githubusercontent.com/49548116/56028518-4272cf80-5d53-11e9-8e40-a11503cc2894.png">

**Comment by mitmul** [comment]
@nagayamashota ご指摘ありがとうございます。 #7 にて修正させていただきます。
